const THEME_FEATURE_FLAG =
  process.env.NEXT_PUBLIC_ENABLE_THEME_FEATURE ??
  process.env.VITE_ENABLE_THEME_FEATURE;

export const IS_THEME_FEATURE_ENABLED = THEME_FEATURE_FLAG !== "false";

export const IS_CLIENT_RUNTIME_THEME_ENABLED =
  IS_THEME_FEATURE_ENABLED &&
  process.env.NEXT_PUBLIC_ENABLE_RUNTIME_THEME !== "false";
